version: "3.9"

services:
  ms-catalogo:
    build: ./ms-catalogo
    ports:
      - "5001:5001"

  ms-pagos:
    build: ./ms-pagos
    ports:
      - "5002:5002"

  ms-compras:
    build: ./ms-compras
    ports:
      - "5003:5003"

  ms-inventario:
    build: ./ms-inventario
    ports:
      - "5004:5004"

  orquestador:
    build: ./orquestador
    ports:
      - "5000:5000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"

networks:
  default:
    name: saga-network
